
import StreamVideoProvider from '@/providers/stream-client-provider'
import { Metadata } from 'next';
import React, { ReactNode } from 'react'


export const metadata: Metadata = {
  title: "TS Bridge Meet",
  description: "Generated by Ariz Shahid",
  icons: {
    icon: '/images/logo.png'
  }
};


const RootLayout = ({children} : {children: ReactNode}) => {
  return (
    <main>
      <StreamVideoProvider>

      {children}
      </StreamVideoProvider>
      </main>
  )
}

export default RootLayout